### PR TITLE
Cleaned schematic & changed antenna path on Board

### PR DESCRIPTION
**Pull request by madmax76**
Hi Scott,

As discussed, I cleaned the schematic for readability and on the side I tried to improve antenna performance by making the antenna track on the board a bit more smooth.

I've done the changes in Eagle 9.2.1

Please have a look,
Max

### CODE REVIEW

**Comment by statts** [comment]
Hi Max,
That's great - will take a look at these changes shortly,
Thanks!
Scott

**Comment by statts** [comment]
Hi Max,
The schematic looks good. A couple of questions on the board:
1) I like the new curved antenna trace, but is the new antenna trace 50 ohm impedence? (the trace looks a lot thicker than in my original?)
2) When I do a DRC check of the board (tools->DRC check, using the MultiCB standard 2 layer DRU file: https://www.multi-circuit-boards.eu/en/support/pcb-data/eagle.html) I get a couple of new errors on keepout overlap around the 0402 capacitors under the antenna, I think you moved these to be closed together, but I think they might be a little too close.  Also, bear in mind that I had to hand solder these components on for my prototype testing and these things are so small you could lose them if you breath out near them! So having them too close together might make it more difficult to prototype (though manufacturing won't be affected by this of course)
3) Aside from the antenna trace and the positioning of the capacitors, were there any other changes to the board?

Thanks,

Scott

**Comment by madmax76** [comment]
> but is the new antenna trace 50 ohm impedence? (the trace looks a lot thicker than in my original?)

If the track-length (+/- 20mm) is much less than the wavelength (34,5 cm) the impedence is not that critical.

> keepout overlap around the 0402 capacitors under the antenna

Yes, the margins for these capacitors is designed for wave-soldering. Manual and reflow soldering is not a problem. (I've seen how you've managed to solder the sensors, this is much easier)

> any other changes to the board?

Everything else should be oke. I am ordering a few in China and keep you posted.

**Comment by statts** [comment]
Hi Max,
Great, thanks.  Btw, I found multi-curcuit boards good for PCB printing:
https://www.multi-circuit-boards.eu/en/index.html

In case the China PCB printing doesn't work out or takes too long.  If not,
let me know who you used I might use them myself for my next board!

Cheers,
Scott

**Pull request merged**
